export const FETCH_SURVEY_DATA_SUCCESS = "FETCH_SURVEY_DATA_SUCCESS";
export const FETCH_SURVEY_DATA_FAIL = "FETCH_SURVEY_DATA_FAIL";

export const FETCH_VOTE_SUCCESS = "FETCH_VOTE_SUCCESS";
export const FETCH_VOTE_FAIL = "FETCH_VOTE_FAIL";
